apiVersion: v1
kind: PersistentVolume
metadata:
  name: identity-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    type: DirectoryOrCreate
    path: /pgdata