apiVersion: v1
kind: PersistentVolume
metadata: 
  name: identity-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    type: DirectoryOrCreate
    path: /text

