services:
  identityservice:
    # image: dducthang/identity-service:v1.4
    image: dducthang/hecate:v1.0
    build:
      context: ../
      dockerfile: docker/Dockerfile.Hecate
    env_file: ./.env
    ports:
      - 9002:443
      - 5002:80
    depends_on:
      - database
    volumes:
      - text:/app/Text

  database:
    image: dducthang/hecate-db:v1.0
    build:
      context: ../
      dockerfile: docker/Dockerfile.HecateDb
    env_file: ./.env
    ports:
      - 7228:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ../docker-mount/pgdata:/var/lib/postgresql/data # Mount host directory as a volume

volumes:
  text:
  pgdata:
