apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-db
spec:
  selector:
    matchLabels:
      label: identity-db
  template:
    metadata:
      labels:
        label: identity-db
    spec:
      containers:
        - name: identity-db
          image: dducthang/identity-database:v1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: db-volume
              mountPath: /pgdata
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName:  identity-db-pvc