apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: identity-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: identity-db-pv
  storageClassName: standard