apiVersion: v1
kind: Service
metadata:
  name: hecate.identity.service
  labels:
    group: identity
spec:
  selector:
    label: identity-service
  ports:
    - protocol: 'TCP'
      port: 9003
      targetPort: 443
      name: https
    - protocol: 'TCP'
      port: 5003
      targetPort: 80
      name: http
  type: LoadBalancer