apiVersion: v1
kind: Service
metadata:
  name: identity-service
  labels:
    group: identity
spec:
  selector:
    label: identity-service-label
  ports:
    - protocol: 'TCP'
      port: 7225
      targetPort: 443
      name: https
    - protocol: 'TCP'
      port: 5090
      targetPort: 80
      name: http
  type: LoadBalancer