apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: identity-pv
  storageClassName: standard
