// <auto-generated />
using System;
using IdentityServer.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityServer.Models.Context.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240331034455_AddUserTable")]
    partial class AddUserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identitydb")
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ApiResource", b =>
                {
                    b.Property<Guid>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Secret")
                        .HasColumnType("uuid");

                    b.HasKey("Index");

                    b.ToTable("ApiResource", "identitydb");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ApiScope", b =>
                {
                    b.Property<Guid>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.ToTable("ApiScope", "identitydb");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ApiScopeResource", b =>
                {
                    b.Property<Guid>("ApiScopeIndex")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiResourceIndex")
                        .HasColumnType("uuid");

                    b.HasKey("ApiScopeIndex", "ApiResourceIndex");

                    b.HasIndex("ApiResourceIndex");

                    b.ToTable("ApiScopeResource", "identitydb");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.Client", b =>
                {
                    b.Property<Guid>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.ToTable("Client", "identitydb");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ClientGrantType", b =>
                {
                    b.Property<Guid>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientIndex")
                        .HasColumnType("uuid");

                    b.Property<string>("GrantType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.HasIndex("ClientIndex");

                    b.ToTable("ClientGrantType", "identitydb");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ClientScope", b =>
                {
                    b.Property<Guid>("ClientIndex")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiScopeIndex")
                        .HasColumnType("uuid");

                    b.HasKey("ClientIndex", "ApiScopeIndex");

                    b.HasIndex("ApiScopeIndex");

                    b.ToTable("ClientScope", "identitydb");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ClientSecret", b =>
                {
                    b.Property<Guid>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientIndex")
                        .HasColumnType("uuid");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.HasIndex("ClientIndex");

                    b.ToTable("ClientSecret", "identitydb");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.User", b =>
                {
                    b.Property<Guid>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.ToTable("User", "identitydb");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ApiScopeResource", b =>
                {
                    b.HasOne("IdentityServer.Models.DomainClasses.ApiResource", "ApiResource")
                        .WithMany("ApiScopeResources")
                        .HasForeignKey("ApiResourceIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityServer.Models.DomainClasses.ApiScope", "ApiScope")
                        .WithMany("ApiScopeResources")
                        .HasForeignKey("ApiScopeIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiResource");

                    b.Navigation("ApiScope");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ClientGrantType", b =>
                {
                    b.HasOne("IdentityServer.Models.DomainClasses.Client", "Client")
                        .WithMany("ClientGrantTypes")
                        .HasForeignKey("ClientIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ClientScope", b =>
                {
                    b.HasOne("IdentityServer.Models.DomainClasses.ApiScope", "ApiScope")
                        .WithMany("ClientScopes")
                        .HasForeignKey("ApiScopeIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityServer.Models.DomainClasses.Client", "Client")
                        .WithMany("ClientScopes")
                        .HasForeignKey("ClientIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiScope");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ClientSecret", b =>
                {
                    b.HasOne("IdentityServer.Models.DomainClasses.Client", "Client")
                        .WithMany("ClientSecrets")
                        .HasForeignKey("ClientIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ApiResource", b =>
                {
                    b.Navigation("ApiScopeResources");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.ApiScope", b =>
                {
                    b.Navigation("ApiScopeResources");

                    b.Navigation("ClientScopes");
                });

            modelBuilder.Entity("IdentityServer.Models.DomainClasses.Client", b =>
                {
                    b.Navigation("ClientGrantTypes");

                    b.Navigation("ClientScopes");

                    b.Navigation("ClientSecrets");
                });
#pragma warning restore 612, 618
        }
    }
}
